import { expect, test } from "@playwright/test";
const slugs=["slope","2048","curve-rush","tap-road","head-basketball","escape-road","trap-the-cat","suika-game"];

test("production home geometry, groups, and lazy main frame",async({page})=>{const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});await page.setViewportSize({width:1464,height:900});await page.goto("/");await expect(page.getByRole("heading",{level:1,name:"Play Krillion Online"})).toBeVisible();await expect(page.getByRole("button",{name:"Play Now"})).toBeVisible();await expect(page.locator("iframe[data-game-frame]")).toHaveCount(0);expect(await page.locator("main").evaluate(n=>Math.round(n.getBoundingClientRect().width))).toBe(1400);await expect(page.getByRole("heading",{name:"Featured Games"}).locator("xpath=following-sibling::div/a")).toHaveCount(6);await expect(page.getByRole("heading",{name:"New Games"}).locator("xpath=following-sibling::div/a")).toHaveCount(6);await expect(page.getByRole("heading",{name:"Recommended Games"}).locator("xpath=following-sibling::div/a")).toHaveCount(6);expect(errors).toEqual([]);await page.getByRole("button",{name:"Play Now"}).click();const frame=page.locator("iframe[data-game-frame]");await expect(frame).toHaveCount(1);await expect(frame).toHaveAttribute("src","https://www.krillion.org/play/daily/");await expect(frame).toHaveAttribute("sandbox",/allow-scripts/);expect((await frame.getAttribute("sandbox"))?.match(/allow-popups|allow-top-navigation/)).toBeNull()});

test("all additions keep identity and create one configured frame",async({page})=>{for(const slug of slugs){await page.goto(`/games/${slug}`);await expect(page.getByRole("button",{name:"Play Now"})).toHaveCount(1);await expect(page.locator("iframe[data-game-frame]")).toHaveCount(0);await page.getByRole("button",{name:"Play Now"}).click();await expect(page.locator("iframe[data-game-frame]")).toHaveCount(1);await expect(page.locator("iframe[data-game-frame]")).toHaveAttribute("src",`https://azgames.io/${slug}.embed`)}});

test("games grid is 6, 4, and 2 columns",async({page})=>{await page.setViewportSize({width:1464,height:900});await page.goto("/games");const grid=page.locator("main div").filter({has:page.getByRole("link",{name:/Slope/})}).last();expect(await grid.evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(" ").length)).toBe(6);await page.setViewportSize({width:1024,height:768});expect(await grid.evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(" ").length)).toBe(4);await page.setViewportSize({width:768,height:900});expect(await grid.evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(" ").length)).toBe(2)});

test("mobile layout disables sticky, preserves section order, and shows video directly",async({page})=>{await page.setViewportSize({width:768,height:900});await page.goto("/games/slope");const h=await page.locator("main h2").evaluateAll(ns=>ns.map(n=>n.textContent?.trim()));expect(h.indexOf("Recommended Games")).toBeLessThan(h.indexOf("How Slope works"));expect(h.indexOf("Watch Slope gameplay")).toBeLessThan(h.indexOf("Featured Games"));expect(h.indexOf("Featured Games")).toBeLessThan(h.indexOf("New Games"));await expect(page.locator("iframe[src*='youtube-nocookie.com/embed/']")).toHaveCount(1);await expect(page.getByRole("button",{name:/Play video|Retry video/i})).toHaveCount(0)});

test("each game exposes its own ratings panel after New Games",async({page})=>{for(const route of ["/",...slugs.map(slug=>`/games/${slug}`)]){await page.goto(route);const headings=await page.locator("aside h2").evaluateAll(nodes=>nodes.map(node=>node.textContent?.trim()));expect(headings.indexOf("Player Ratings")).toBe(headings.indexOf("New Games")+1);await expect(page.getByRole("heading",{name:"Player Ratings"})).toHaveCount(1)}});

test("fullscreen icons differ and menu closes with Escape",async({page})=>{await page.setViewportSize({width:1024,height:768});await page.goto("/");const paths=await page.locator("[title$='Fullscreen'] svg").evaluateAll(s=>s.map(x=>x.innerHTML.replace(/\s+/g," ")));expect(paths).toHaveLength(2);expect(paths[0]).not.toBe(paths[1]);const menu=page.getByRole("button",{name:"Menu"});await menu.click();await expect(menu).toHaveAttribute("aria-expanded","true");await page.keyboard.press("Escape");await expect(menu).toHaveAttribute("aria-expanded","false")});

test("Guide and Legal routes render without forms",async({page})=>{for(const route of ["/guides","/guides/how-to-play-krillion","/guides/krillion-scoring-and-rare-answers","/guides/krillion-loading-and-input-help","/privacy","/terms","/copyright","/about","/contact"]){const response=await page.goto(route);expect(response?.status()).toBe(200);await expect(page.locator("h1")).toHaveCount(1);await expect(page.locator("form,input,textarea")).toHaveCount(0)}});

test("Guide index uses gameplay cards and visible breadcrumbs",async({page})=>{await page.setViewportSize({width:1464,height:900});await page.goto("/guides");await expect(page.getByRole("navigation",{name:"Breadcrumb"})).toContainText("Home");const cards=page.locator("main a[href^='/guides/']");await expect(cards).toHaveCount(3);expect(await cards.locator("img").evaluateAll(images=>images.map(image=>image.getAttribute("src")))).toEqual(["/images/games/krillion/gameplay-1.webp","/images/games/krillion/gameplay-2.webp","/images/games/krillion/gameplay-3.webp"]);expect(await cards.first().locator("xpath=..").evaluate(node=>getComputedStyle(node).gridTemplateColumns.split(" ").length)).toBe(3);await page.setViewportSize({width:768,height:900});expect(await cards.first().locator("xpath=..").evaluate(node=>getComputedStyle(node).gridTemplateColumns.split(" ").length)).toBe(1);expect(await page.locator("html").evaluate(node=>node.scrollWidth-node.clientWidth)).toBe(0)});

test("Guide detail exposes article metadata and responsive anchor rail",async({page})=>{await page.setViewportSize({width:1464,height:900});await page.goto("/guides/how-to-play-krillion");await expect(page.getByRole("navigation",{name:"Breadcrumb"})).toContainText("How to Play Krillion");await expect(page.getByText("Checkpoint Nomad",{exact:true})).toBeVisible();await expect(page.locator("time[datetime='2026-09-22']").first()).toContainText("September 22, 2026");await expect(page.getByLabel("Guide tags").locator("li")).toHaveCount(3);const toc=page.getByRole("navigation",{name:"On this page"});const sidebar=toc.locator("xpath=..");await expect(toc.getByRole("link")).toHaveCount(7);expect(await sidebar.evaluate(node=>getComputedStyle(node).position)).toBe("sticky");expect(await sidebar.evaluate(node=>getComputedStyle(node).maxHeight)).not.toBe("none");expect(await toc.locator("xpath=../..").evaluate(node=>getComputedStyle(node).gridTemplateColumns.split(" ").length)).toBe(2);await page.evaluate(()=>scrollTo(0,1400));const stickyTop=await sidebar.evaluate(node=>Math.round(node.getBoundingClientRect().top));expect(stickyTop).toBeGreaterThanOrEqual(90);expect(stickyTop).toBeLessThanOrEqual(94);await page.evaluate(()=>scrollTo(0,0));await page.setViewportSize({width:768,height:900});expect(await sidebar.evaluate(node=>getComputedStyle(node).position)).toBe("static");expect(await sidebar.evaluate(node=>getComputedStyle(node).maxHeight)).toBe("none");expect(await toc.evaluate(node=>node.getBoundingClientRect().top)).toBeLessThan(await page.locator("main img").first().evaluate(node=>node.getBoundingClientRect().top));expect(await page.locator("html").evaluate(node=>node.scrollWidth-node.clientWidth)).toBe(0)});

test("Legal pages are detailed, dated, and connected by breadcrumbs",async({page})=>{const minimumSections:Record<string,number>={"/privacy":11,"/terms":11,"/copyright":7,"/about":5,"/contact":5};for(const [route,count] of Object.entries(minimumSections)){await page.goto(route);await expect(page.getByRole("navigation",{name:"Breadcrumb"})).toContainText("Home");await expect(page.locator("time[datetime='2026-09-22']").first()).toContainText("September 22, 2026");await expect(page.locator("article > section")).toHaveCount(count);await expect(page.getByRole("navigation",{name:"Site policies"}).getByRole("link")).toHaveCount(4)}await page.goto("/about");await expect(page.getByRole("heading",{level:1,name:"About Checkpoint Nomad"})).toBeVisible();await expect(page.getByText(/started publishing these guides in early 2026/i)).toBeVisible();await page.goto("/contact");await expect(page.getByText("wyong@testkrillion.com",{exact:true})).toBeVisible();await expect(page.locator("a[href^='mailto:']")).toHaveCount(0)});
